image: node:10

test:
  script:
   - npm ci
   - npm run test
  coverage: /^Statements\s*:\s*([^%]+)/

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

npm:
  stage: deploy
  only:
    - tags
  script:
    - npm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
    - npm publish

dockerhub:
  stage: deploy
  image: docker:latest
  services:
      - docker:dind
  only:
    - tags
  script:
    - VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - echo $VERSION
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t ramielcreations/caravaggio:$VERSION .
    - docker tag ramielcreations/caravaggio:$VERSION ramielcreations/caravaggio:latest
    - docker images
    - docker push ramielcreations/caravaggio:$VERSION
    - docker push ramielcreations/caravaggio:latest


# Gitlab Pages
pages:
  only:
    - master
  script:
    - cd website
    - npm install
    - npm run build
    - cp -r build/caravaggio ../public
  artifacts:
    paths:
      - public
