image: node:10

test:
  script:
   - npm ci
   - npm run test
  coverage: /^Statements\s*:\s*([^%]+)/

include:
  - template: Code-Quality.gitlab-ci.yml

#####################
# Publish on NPM
#####################
npm:
  stage: deploy
  only:
    - tags
  script:
    - npm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
    - npm publish


#####################
# Publish on ZEIT NOW
# Mainly used to provide 
# example on the website
#####################
now-master:
  stage: deploy
  only:
    - master
  script:
    - npm install -g --unsafe-perm now
    - now deploy -t $NOW_TOKEN -m VERSION=$CI_COMMIT_SHORT_SHA -f
    - now alias caravaggio-$CI_COMMIT_REF_NAME.now.sh -t $NOW_TOKEN

now-tag:
  stage: deploy
  only:
    - tags
  script:
    - export VERSION=`echo $CI_COMMIT_TAG | sed -r 's/[.]+/-/g'`
    - npm install -g --unsafe-perm now
    - now deploy -t $NOW_TOKEN -m VERSION=$VERSION -f
    - now alias caravaggio-$VERSION.now.sh -t $NOW_TOKEN
    - now alias caravaggio.now.sh -t $NOW_TOKEN

now-resources-master:
  stage: deploy
  only:
    - master
  script:
    - cd website/docs/assets/example
    - npm install -g --unsafe-perm now
    - now deploy -t $NOW_TOKEN -m VERSION=$CI_COMMIT_SHORT_SHA -f
    - now alias cvg-res-$CI_COMMIT_REF_NAME.now.sh -t $NOW_TOKEN

now-resources-tag:
  stage: deploy
  only:
    - tags
  script:
    - cd website/docs/assets/example
    - export VERSION=`echo $CI_COMMIT_TAG | sed -r 's/[.]+/-/g'`
    - npm install -g --unsafe-perm now
    - now deploy -t $NOW_TOKEN -m VERSION=$VERSION -f
    - now alias cvg-res-$VERSION.now.sh -t $NOW_TOKEN
    - now alias cvg-res.now.sh -t $NOW_TOKEN

#####################
# Publish on Docker
#####################
docker-next:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:next .
    - docker push $CI_REGISTRY_IMAGE:next

docker-tag:
  stage: deploy
  image: docker:latest
  services:
      - docker:dind
  only:
    - tags
  script:
    - VERSION=$CI_COMMIT_TAG
    - echo $VERSION
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t ramielcreations/caravaggio:$VERSION .
    - docker tag ramielcreations/caravaggio:$VERSION ramielcreations/caravaggio:latest
    - docker images
    - docker push ramielcreations/caravaggio:$VERSION
    - docker push ramielcreations/caravaggio:latest


# Gitlab Pages
pages:
  only:
    - master
  script:
    - cd website
    - npm install
    - npm run build
    - cp -r build/caravaggio ../public
  artifacts:
    paths:
      - public
